export class ProjectIO {
  constructor(editor, historyManager, showStatus) {
    this.editor = editor;
    this.history = historyManager;
    this.showStatus = showStatus;
    this.fileInput = document.getElementById("fileInput");
    this.latexInput = document.getElementById("latexInput");
  }

  setup() {
    this.fileInput?.addEventListener("change", (e) => this.handleFileLoad(e));
    this.latexInput?.addEventListener("change", (e) => this.handleLatexImport(e));
  }

  saveProject() {
    const state = this.editor.getState();
    const timestamp = this.getTimestamp();

    const projectData = {
      version: "1.0",
      created: new Date().toISOString(),
      title: "MathScript Project",
      content: state
    };

    this.downloadFile(
      JSON.stringify(projectData, null, 2),
      `mathscript-project-${timestamp}.json`,
      "application/json"
    );

    this.showStatus("Project saved to downloads");
  }

  loadProject() {
    this.fileInput?.click();
  }

  handleFileLoad(e) {
    const file = e.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target.result);

        if (data.content && Array.isArray(data.content)) {
          this.editor.restoreState(data.content);
          this.history.save(this.editor.getState());
          this.showStatus("Project loaded successfully");
        } else {
          this.showStatus("Invalid project file format");
        }
      } catch (error) {
        this.showStatus("Error loading project file");
        console.error("Load error:", error);
      }
    };

    reader.readAsText(file);
    e.target.value = "";
  }

  exportLatex() {
    const latex = this.editor.lastLatex;

    if (!latex.trim()) {
      this.showStatus("Nothing to export");
      return;
    }

    const timestamp = this.getTimestamp();
    const latexDocument = this.buildLatexDocument(latex);

    this.downloadFile(latexDocument, `mathscript-export-${timestamp}.tex`, "text/plain");
    this.showStatus("LaTeX exported to downloads");
  }

  importLatex() {
    this.latexInput?.click();
  }

  handleLatexImport(e) {
    const file = e.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const latexContent = event.target.result;
        const content = this.parseLatexContent(latexContent);

        if (content.trim()) {
          this.editor.restoreState([{ value: content.trim(), isText: false }]);
          this.history.save(this.editor.getState());
          this.showStatus("LaTeX imported successfully");
        } else {
          this.showStatus("No content found in LaTeX file");
        }
      } catch (error) {
        this.showStatus("Error importing LaTeX file");
        console.error("Import error:", error);
      }
    };

    reader.readAsText(file);
    e.target.value = "";
  }

  copyLatex() {
    const latex = this.editor.lastLatex;

    if (!latex.trim()) {
      this.showStatus("Nothing to copy");
      return;
    }

    navigator.clipboard.writeText(latex)
      .then(() => this.showStatus("LaTeX copied to clipboard"))
      .catch(() => this.showStatus("Failed to copy LaTeX"));
  }

  copyPlainText() {
    const text = this.editor.getPlainText();

    if (!text.trim()) {
      this.showStatus("Nothing to copy");
      return;
    }

    navigator.clipboard.writeText(text)
      .then(() => this.showStatus("Plain text copied to clipboard"))
      .catch(() => this.showStatus("Failed to copy plain text"));
  }

  clearAll() {
    if (confirm("Clear all content? This cannot be undone.")) {
      this.editor.stack.innerHTML = "";
      this.editor.addRow();
      this.history.save(this.editor.getState());
      this.showStatus("Cleared all content");
    }
  }

  downloadFile(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  buildLatexDocument(latex) {
    const date = new Date().toLocaleDateString();

    return `% MathScript Export - ${date}
% Generated by MathScript - Digital Math Notebook
% © 2025 Théophile Jérôme-Rocher

\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}
\\usepackage[utf8]{inputenc}

\\title{Mathematical Notes}
\\author{MathScript}
\\date{${date}}

\\begin{document}
\\maketitle

${latex}

\\end{document}`;
  }

  parseLatexContent(latexContent) {
    const documentMatch = latexContent.match(/\\begin\{document\}([\s\S]*?)\\end\{document\}/);
    let content = documentMatch ? documentMatch[1].trim() : latexContent;

    content = content.replace(/\\maketitle/g, '');
    content = content.replace(/\\title\{[^}]*\}/g, '');
    content = content.replace(/\\author\{[^}]*\}/g, '');
    content = content.replace(/\\date\{[^}]*\}/g, '');

    return content.trim();
  }

  getTimestamp() {
    return new Date().toISOString().slice(0, 19).replace(/:/g, '-');
  }
}
